# Generated by Django 4.0.3 on 2023-10-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('agence_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agence_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReclamationObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reclamation_object_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reclamation_reference', models.CharField(max_length=255, unique=True)),
                ('reclamation_date', models.DateField(default=None, null=True)),
                ('reclamation_firstname', models.CharField(max_length=255)),
                ('reclamation_lastname', models.CharField(max_length=255)),
                ('reclamation_adresse', models.CharField(default=None, max_length=255, null=True)),
                ('reclamation_tel', models.CharField(max_length=255)),
                ('reclamation_mail', models.CharField(default=None, max_length=255, null=True)),
                ('reclamation_customer', models.BooleanField(default=False)),
                ('reclamation_account_number', models.CharField(default=None, max_length=255, null=True)),
                ('reclamation_detail', models.TextField()),
                ('reclamation_response', models.CharField(default=None, max_length=255, null=True)),
                ('reclamation_rejected', models.BooleanField(default=False)),
                ('reclamation_closed', models.BooleanField(default=False)),
                ('reclamation_userassigned', models.IntegerField(default=None, null=True)),
                ('reclamation_code_agent', models.CharField(default='', max_length=255)),
                ('reclamation_agence', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.agence')),
                ('reclamation_object', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.reclamationobject')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agent_code', models.CharField(max_length=30, unique=True)),
                ('agent_name', models.CharField(max_length=255)),
                ('agent_mail', models.CharField(max_length=255)),
                ('agent_agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='base.agence')),
            ],
        ),
    ]
